//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionQuestionAnswer
    {
        public int Inspection_Id { get; set; }
        public int Inspector_Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Question_Id { get; set; }
        public string Answer { get; set; }
    
        public virtual Planning Planning { get; set; }
        public virtual InspectionQuestion InspectionQuestion { get; set; }
    }
}
