//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection : Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspection()
        {
            this.Planning = new HashSet<Planning>();
            this.InspectionQuestion = new HashSet<InspectionQuestion>();
        }
    
        public string Name { get; set; }
        public string Website { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Status_Status { get; set; }
        public int Customer_Id { get; set; }
        public string Instructions { get; set; }
    
        public virtual InspectionStatus Status { get; set; }
        public virtual Customer Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planning> Planning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionQuestion> InspectionQuestion { get; set; }
    }
}
